export const FETCH_BOARDS = "FETCH_BOARDS";
export const DELETE_BOARD = "DELETE_BOARDS";
export const CREATE_BOARD = "CREATE_BOARD";
export const RENAME_BOARD = "RENAME_BOARD";

export const FETCH_USERS = "FETCH_USERS";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";

export const FETCH_CARDS = "FETCH_CARDS";
export const CREATE_CARD = "CREATE_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const RENAME_CARD = "RENAME_CARD";
export const ADD_USER_TO_CARD = "ADD_USER_TO_CARD";
export const REMOVE_USER_FROM_CARD = "REMOVE_USER_FROM_CARD";
export const EDIT_DESCRIPTION_IN_CARD = "EDIT_DESCRIPTION_IN_CARD";

export const FETCH_LISTS = "FETCH_LISTS";
export const CREATE_LIST = "CREATE_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const RENAME_LIST = "RENAME_LIST";

export const REQUEST_DATA = "REQUEST_DATA";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";
export const REQUEST_DATA_ERROR = "REQUEST_DATA_ERROR";

export const POP_OVER_LIST_MENU = "POP_OVER_LIST_MENU";
export const POP_OVER_CARD_EDITOR = "POP_OVER_CARD_EDITOR";

export const CHECK_ONCLICK_BOARD = "CHECK_ONCLICK_BOARD";
export const ONCLICK_LIST_CREATOR = "ONCLICK_LIST_CREATOR";
export const ONCLICK_CARD_CREATOR = "ONCLICK_CARD_CREATOR";
export const ONCLICK_BOARD_MENU = "ONCLICK_BOARD_MENU";




